### ISSUE TITLE
I got this error for some reason...

### ISSUE THREAD

**Issue by seriaati** [Kenny2github/discord-ext-slash#9]
```
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\seria\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\seria\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\slash\__init__.py", line 1289, in on_ready
    await self.register_commands()
  File "C:\Users\seria\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\slash\__init__.py", line 1408, in register_commands
    guild_cmds = await self.http.request(route)
  File "C:\Users\seria\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
```

**Comment by retronbv** [comment]
It seems your bot user is missing the `application.commands` permission when you invited it to your server. Create a new oauth url with this permission and it should work.
